<?php

namespace ContainerErxTymG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QDIaAYMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qDIaAYM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qDIaAYM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\GuestbookController::approve' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'App\\Controller\\GuestbookController::index' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'App\\Controller\\GuestbookController::remove' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'App\\Controller\\HomeController::admin_login' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\GuestbookController:approve' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'App\\Controller\\GuestbookController:index' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'App\\Controller\\GuestbookController:remove' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'App\\Controller\\HomeController:admin_login' => ['privates', '.service_locator.7J2jyQg', 'get_ServiceLocator_7J2jyQgService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\GuestbookController::approve' => '?',
            'App\\Controller\\GuestbookController::index' => '?',
            'App\\Controller\\GuestbookController::remove' => '?',
            'App\\Controller\\HomeController::admin_login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\GuestbookController:approve' => '?',
            'App\\Controller\\GuestbookController:index' => '?',
            'App\\Controller\\GuestbookController:remove' => '?',
            'App\\Controller\\HomeController:admin_login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
