<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNYExxcT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNYExxcT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNYExxcT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNYExxcT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNYExxcT\App_KernelDevDebugContainer([
    'container.build_hash' => 'NYExxcT',
    'container.build_id' => '57e7d0fc',
    'container.build_time' => 1666254198,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNYExxcT');
