<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'guestbook.listing' => [[], ['_controller' => 'App\\Controller\\GuestbookController::index'], [], [['text', '/guestbook/']], [], [], []],
    'guestbook.create' => [[], ['_controller' => 'App\\Controller\\GuestbookController::create'], [], [['text', '/guestbook/create']], [], [], []],
    'guestbook.approve' => [['gb_id'], ['_controller' => 'App\\Controller\\GuestbookController::approve'], [], [['variable', '/', '[^/]++', 'gb_id', true], ['text', '/guestbook/approve']], [], [], []],
    'guestbook.remove' => [['gb_id'], ['_controller' => 'App\\Controller\\GuestbookController::remove'], [], [['variable', '/', '[^/]++', 'gb_id', true], ['text', '/guestbook/remove']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'guest_login' => [[], ['_controller' => 'App\\Controller\\HomeController::guest_login'], [], [['text', '/guest_login']], [], [], []],
    'admin_login' => [[], ['_controller' => 'App\\Controller\\HomeController::admin_login'], [], [['text', '/admin_login']], [], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\HomeController::logout'], [], [['text', '/logout']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
